import { BannerTheme, AspectRatioOption } from '../types';

export const BANNER_THEMES: BannerTheme[] = [
  {
    id: 'cyber-quantum',
    name: 'Cyber Quantum',
    description: 'Electric cyan, cobalt blue, and golden fusion accents in deep obsidian space',
    primaryGlow: '#00f2fe',
    secondaryGlow: '#4facfe',
    accentGlow: '#ffd200',
    textColor: '#ffffff',
    bgDark: '#04070d',
    bgMid: '#0c1424',
    rimColorLeft: '#38bdf8', // Adventurous cyan rim
    rimColorCenter: '#00f2fe', // Electric cyan/white
    rimColorRight: '#f59e0b', // Amber action rim
  },
  {
    id: 'solar-vanguard',
    name: 'Solar Vanguard',
    description: 'Molten gold, incandescent amber, and plasma crimson with industrial steel',
    primaryGlow: '#f59e0b',
    secondaryGlow: '#ef4444',
    accentGlow: '#fbbf24',
    textColor: '#fef3c7',
    bgDark: '#0b0806',
    bgMid: '#1a120c',
    rimColorLeft: '#06b6d4',
    rimColorCenter: '#f59e0b',
    rimColorRight: '#ea580c',
  },
  {
    id: 'stark-titanium',
    name: 'Stark Titanium',
    description: 'Monochrome tungsten, brushed titanium, hyper white, and cold laser ice',
    primaryGlow: '#e2e8f0',
    secondaryGlow: '#94a3b8',
    accentGlow: '#38bdf8',
    textColor: '#ffffff',
    bgDark: '#030508',
    bgMid: '#0f172a',
    rimColorLeft: '#93c5fd',
    rimColorCenter: '#f8fafc',
    rimColorRight: '#67e8f9',
  },
  {
    id: 'neon-ronin',
    name: 'Neon Ronin',
    description: 'Bioluminescent synthwave violet, electric magenta, and spectral teal',
    primaryGlow: '#d946ef',
    secondaryGlow: '#8b5cf6',
    accentGlow: '#06b6d4',
    textColor: '#ffffff',
    bgDark: '#08040d',
    bgMid: '#1e0c2f',
    rimColorLeft: '#22d3ee',
    rimColorCenter: '#ec4899',
    rimColorRight: '#a855f7',
  },
  {
    id: 'stealth-monolith',
    name: 'Stealth Monolith',
    description: 'Deep carbon fiber, subtle emerald matrix conduits, and tactical olive matte',
    primaryGlow: '#10b981',
    secondaryGlow: '#059669',
    accentGlow: '#34d399',
    textColor: '#f0fdf4',
    bgDark: '#030805',
    bgMid: '#091c13',
    rimColorLeft: '#06b6d4',
    rimColorCenter: '#10b981',
    rimColorRight: '#f59e0b',
  },
];

export const ASPECT_RATIOS: AspectRatioOption[] = [
  {
    id: '3:1',
    label: '3:1 Ultra-Wide (GitHub Retina)',
    width: 2400,
    height: 800,
    description: 'Standard 3:1 banner proportion requested, rendered at 2400×800 for pristine 4K display',
  },
  {
    id: '3:1-compact',
    label: '3:1 Standard (1200×400)',
    width: 1200,
    height: 400,
    description: 'Optimized 3:1 file-size format for lightning fast GitHub README load times',
  },
  {
    id: '16:9',
    label: '16:9 Cinematic (1920×1080)',
    width: 1920,
    height: 1080,
    description: 'Full-bleed desktop wallpaper & portfolio hero showcase',
  },
  {
    id: '4:1',
    label: '4:1 Compact Banner (2400×600)',
    width: 2400,
    height: 600,
    description: 'Sleek letterbox header maximizing vertical README space',
  },
];

export const DEFAULT_PINNED_REPOS = [
  {
    name: 'neural-generative-cad',
    description: 'Deep reinforcement learning for automated mechanical generative design & topology optimization.',
    language: 'Python',
    languageColor: '#3572A5',
    stars: 342,
    forks: 48,
    tags: ['ai-engineering', 'mechanical-cad', 'pytorch', 'finite-element'],
  },
  {
    name: 'autonomous-exoskeleton-ros2',
    description: 'Real-time biomechanical sensor fusion & predictive kinematic gait control algorithms for assistive robotics.',
    language: 'C++',
    languageColor: '#f34b7d',
    stars: 521,
    forks: 73,
    tags: ['robotics', 'ros2', 'kinematics', 'control-systems'],
  },
  {
    name: 'hypersonic-aerospace-surrogate',
    description: 'Physics-informed neural networks (PINN) simulating hypersonic shockwaves and thermal barrier dynamics.',
    language: 'Julia',
    languageColor: '#a270ba',
    stars: 289,
    forks: 31,
    tags: ['aerospace', 'pinn', 'cfd', 'surrogate-modeling'],
  },
  {
    name: 'quantum-materials-synth',
    description: 'High-throughput predictive screening of ultra-high-temperature ceramics for next-gen fusion reactors.',
    language: 'Rust',
    languageColor: '#dea584',
    stars: 194,
    forks: 22,
    tags: ['futuristic-research', 'materials-science', 'quantum-sim'],
  },
];
